<html>
<head>
<title>(Protein) ErrTryCatch | System Management</title> 
<link href="psi_devpubs.css" rel="stylesheet" type="text/css">

<!-- BEGIN META DATA -->
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<META NAME="PSITEMPLATE" CONTENT="1006-007 PalmSource_HTML_2003 20041101">
<META NAME="GENERATOR" CONTENT="Quadralay WebWorks AutoMap 2003 for FrameMaker 8.0.6.2138">
<META NAME="LASTUPDATED" CONTENT="11/22/04 11:27:35">
<!-- END META DATA -->
</head>

<body bgcolor="#ffffff" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<a name="992934"></a>

<!-- BEGIN TOPNAV -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td><img src="images/shim.gif" width="7" height="75" border="0" alt=""></td>
<td align="left"><table border="0" cellpadding="0" cellspacing="0" width="744">
<tr>
<td><img name="index_r2_c1" src="images/shim.gif" width="25" height="75" border="0" alt=""></td>
<td valign="top"><table border="0" cellpadding="0" cellspacing="0" width="96">
<tr>
<td><img name="index_r2_c4" src="images/shim.gif" width="96" height="15" border="0" alt=""></td>
</tr>
<tr>
<td><a href="http://www.palmsource.com/"><img name="ps_logo" src="images/ps_logo.gif" width="96" height="54" border="0" alt=""></a></td>
</tr>

</table>
</td>

<td><table border="0" cellpadding="0" cellspacing="0" width="30">
<td><img name="index_x" src="images/shim.gif" width="30" height="75" border="0" alt=""></td>
</table></td>

<!--BEGIN MASTHEAD-->
<td><table border="0" cellpadding="0" cellspacing="0" width="96">
<tr>
<td><img name="index_x" src="images/shim.gif" width="615" height="5" border="0" alt=""></td>
</tr>
<tr>
<td>
<!--BEGIN BOOK NAVIGATION-->
<span class="nav">
<A href="http://www.palmos.com/dev/support/docs/">Documentation</a>&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="SysMgt_TOC.html">Table of Contents</a>&nbsp;&nbsp;
             |&nbsp;&nbsp;<a href="ErrorMgr.html">&lt;&nbsp;Previous</a>&nbsp;&nbsp;
             |&nbsp;&nbsp;<a href="ExpansionMgr.html">Next&nbsp;&gt;</a>&nbsp;&nbsp;
             |&nbsp;&nbsp;<a href="SysMgt_IX.html">Index</a>
</span>
<!--END BOOK NAVIGATION-->
</tr>
<tr>
<td>
<!--BEGIN PAGE TITLE-->
<h2 class="PageTitle">24 &nbsp;&nbsp;
ErrTryCatch</h2></td>
<!--END PAGE TITLE-->
</tr>
<tr>
<td>
<!--BEGIN BOOK TITLE-->
<p class="BookTitle">System Management</p>
<p class="SubTitle">Exploring Palm OS&#174; </p>
<!--END BOOK TITLE-->
</td>
</tr>
<tr>
<td><img name="index_x" src="images/shim.gif" width="615" height="5" border="0" alt=""></td>
</tr>
</table>
</td>
<!--END MASTHEAD-->
</tr>
</table>
<img name="dashes" src="images/dashes.gif" width="744" height="3" border="0" alt=""></td>
</tr>
</table>
<!-- END TOPNAV -->

<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td valign="top" width="5"><img name="index_x" src="images/shim.gif" width="5" height="33" border="0" alt=""></td>

<!--BEGIN SIDETOC-->
<td valign="top" width="175">
<div id="sidetoc" valign="bottom">
<h1 class="SideTOC1-PartTab"><a href="SysMgt_Part2.html">Part II: Reference</a> </h1>
<h1 class="SideTOC1"><a href="ErrTryCatch.html">24  ErrTryCatch</a></h1>

   <h2 class="SideTOC2"><a href="#992942">
   ErrTryCatch Structures and Types</a></h2>

      <h3 class="SideTOC3"><a href="#992975">
      ErrExceptionType</a></h3>

      <h3 class="SideTOC3"><a href="#993019">
      ErrJumpBuf</a></h3>

   <h2 class="SideTOC2"><a href="#993080">
   ErrTryCatch Functions and Macros</a></h2>

      <h3 class="SideTOC3"><a href="#993133">
      ErrCatch</a></h3>

      <h3 class="SideTOC3"><a href="#993175">
      ErrCatchWithAddress</a></h3>

      <h3 class="SideTOC3"><a href="#995308">
      ErrEndCatch</a></h3>

      <h3 class="SideTOC3"><a href="#993485">
      ErrExceptionListAppend</a></h3>

      <h3 class="SideTOC3"><a href="#993527">
      ErrExceptionListGetByThreadID</a></h3>

      <h3 class="SideTOC3"><a href="#993731">
      ErrExceptionListRemove</a></h3>

      <h3 class="SideTOC3"><a href="#993773">
      ErrLongJump</a></h3>

      <h3 class="SideTOC3"><a href="#993823">
      ErrSetJump</a></h3>

      <h3 class="SideTOC3"><a href="#993865">
      ErrThrow</a></h3>

      <h3 class="SideTOC3"><a href="#993907">
      ErrThrowIf</a></h3>

      <h3 class="SideTOC3"><a href="#994145">
      ErrThrowWithAddress</a></h3>

      <h3 class="SideTOC3"><a href="#994191">
      ErrThrowWithHandler</a></h3>

      <h3 class="SideTOC3"><a href="#992930">
      ErrTry</a></h3>

</div>
</td>

<td width="5">&nbsp;&nbsp;</td>
<td width="2" background="images/index_r8_c10.gif"><img src="images/shim.gif" width="2" height="75" border="0" alt=""></td>
<td width="5">&nbsp;&nbsp;</td>

<!--END SIDETOC-->

<td valign="top">

<!--BEGIN CONTENT-->
<div id="content" valign="bottom">
<p><a name="992936"> </a>This chapter describes the Palm OS "Try/Catch" exception-handling mechanism. It is organized into the following sections:</p>
   <blockquote class = "bq"><a name="993050"> </a><a href="ErrTryCatch.html#992942">ErrTryCatch Structures and Types</a></blockquote>
   <blockquote class = "bq"><a name="993086"> </a><a href="ErrTryCatch.html#993080">ErrTryCatch Functions and Macros</a></blockquote>

<p><a name="992938"> </a>The header file <code>ErrTryCatch.h</code> declares the API that this chapter describes.</p>

<p><a name="992940"> </a>For instructions on using these APIs to throw and handle exceptions, see <a href="Debugging.html#1023494">"The Try-and-Catch Mechanism."</a></p>

<h2 class="haH2">
  <a name="992942"> </a>ErrTryCatch Structures and Types <a href="#992934"><span class="nav">^TOP^</span></a>
</h2>


<h3 class="hbH3">
  <a name="992975"> </a>ErrExceptionType Struct <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="992980"> </a>Purpose 
</h4>

<p><a name="997406"> </a>An <code>ErrExceptionType</code> structure is created for each <a href="ErrTryCatch.html#992930"><code>ErrTry</code></a> and <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a> block. At any point in the program, there is a linked list of these structures. An <code>ErrExceptionType</code> structure stores information about the state of the machine (register values, an error code, and the address at which the error occurred) at the start of the <code>ErrTry</code> block.</p>
<h4>
  <a name="992985"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="992988"> </a></code><h4>
  <a name="992990"> </a>Prototype 
</h4>
<pre class="proto"><a name="992993"></a>typedef struct ErrExceptionType {
   struct ErrExceptionType *nextP;
   ErrJumpBuf state;
   int32_t err;
   VAddr errVAddr;
} ErrExceptionType
</pre>
<pre class="proto"><a name="996633"></a>typedef ErrExceptionType *ErrExceptionPtr
</pre>
<h4>
  <a name="992995"> </a>Fields 
</h4>

<dl>
<dt><a name="992998"> </a><code>nextP</code></dt>
<dd><a name="993000"> </a>Next <code>ErrExceptionType</code> structure in the linked list.</dd>

<dt><a name="993002"> </a><code>state</code></dt>
<dd><a name="993004"> </a>Environment storage for <a href="ErrTryCatch.html#993823"><code>ErrSetJump()</code></a>/<a href="ErrTryCatch.html#993773"><code>ErrLongJump()</code></a>.</dd>

<dt><a name="993006"> </a><code>err</code></dt>
<dd><a name="993008"> </a>Error code.</dd>

<dt><a name="993010"> </a><code>errVAddr</code></dt>
<dd><a name="993012"> </a>Address reference that caused the fault.</dd>

</dl>

<h3 class="hbH3">
  <a name="993019"> </a>ErrJumpBuf Typedef <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993024"> </a>Purpose 
</h4>

<p><a name="993027"> </a>Contains state information for <a href="ErrTryCatch.html#993823"><code>ErrSetJump()</code></a>/<a href="ErrTryCatch.html#993773"><code>ErrLongJump()</code></a>. Used in the <a href="ErrTryCatch.html#992975"><code>ErrExceptionType</code></a> structure.</p>
<h4>
  <a name="993029"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993032"> </a></code><h4>
  <a name="993034"> </a>Prototype 
</h4>
<pre class="proto"><a name="993037"></a>typedef long *ErrJumpBuf[16]
</pre>

<h2 class="haH2">
  <a name="993080"> </a>ErrTryCatch Functions and Macros <a href="#992934"><span class="nav">^TOP^</span></a>
</h2>


<h3 class="hbH3">
  <a name="993133"> </a>ErrCatch Macro <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993138"> </a>Purpose 
</h4>

<p><a name="997797"> </a>Marks the end of an <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a> block and the beginning of an <code>ErrCatch</code> block.</p>
<h4>
  <a name="993143"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993146"> </a></code><h4>
  <a name="993148"> </a>Prototype 
</h4>
<pre class="proto"><a name="993151"></a>#define ErrCatch (
   <code class="par">inErr</code>
)
</pre>
<h4>
  <a name="993153"> </a>Parameters 
</h4>

<dl>
<dt><a name="993156"> </a><code>&rarr;  <i>inErr</i></code></dt>
<dd><a name="993158"> </a>An exception code identifying the reason for the failure. This is the value supplied to the <a href="ErrTryCatch.html#993865"><code>ErrThrow()</code></a> call that caused the jump to this <code>ErrCatch</code> block.</dd>

</dl>
<h4>
  <a name="993160"> </a>Returns 
</h4>

<p><a name="993163"> </a>Returns nothing.</p>
<h4>
  <a name="993165"> </a>Comments 
</h4>

<p><a name="998047"> </a><code>ErrCatch</code> can only be used in conjunction with <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a> and <code>ErrEndCatch</code>. See the comments under <code>ErrTry</code> for usage instructions.</p>

<p><a name="998048"> </a><code>ErrTry</code>, <code>ErrCatch</code> and <code>ErrThrow</code> are based on <code>setjmp</code> (<a href="ErrTryCatch.html#993823"><code>ErrSetJump()</code></a>) and <code>longjmp</code> (<a href="ErrTryCatch.html#993773"><code>ErrLongJump()</code></a>). At the beginning of an <code>ErrTry</code> block, <code>setjmp</code> saves the machine registers. <code>ErrThrow</code> calls <code>longjmp</code>, which restores the registers and jumps to the beginning of the <code>ErrCatch</code> block. Therefore, any changes in the <code>ErrTry</code> block to variables stored in registers aren't retained when entering the <code>ErrCatch</code> block. </p>

<p><a name="998049"> </a>The solution is to declare variables that you want to use in both the <code>ErrTry</code> and <code>ErrCatch</code> blocks as "volatile". For example:</p>

<div class="CodeRule"><hr></div><pre class="CodeBlock">
volatile long x = 1;  // Declare volatile local variable<a name="998050"> </a>
ErrTry {<a name="998051"> </a>
   x = 100;    // Set local variable in Try<a name="998052"> </a>
   ErrThrow(-1);<a name="998053"> </a>
} <a name="998054"> </a>
ErrCatch(inErr) {<a name="998055"> </a>
   if (x &gt; 1) {    // Use local variable in Catch 	<a name="998056"> </a>
      SysBeep(1);<a name="998057"> </a>
   }<a name="998058"> </a>
} ErrEndCatch<a name="998059"> </a>
</pre><div class="CodeRule"><hr></div>


<p><a name="998060"> </a>If you have many local variables after the <code>ErrCatch</code> you may want to put the <code>ErrTry</code> and <code>ErrCatch</code> in a separate enclosing function.</p>

<h3 class="hbH3">
  <a name="993175"> </a>ErrCatchWithAddress Macro <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993180"> </a>Purpose 
</h4>

<p><a name="993183"> </a>Marks the end of an <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a> block and the beginning of an <code>ErrCatch</code> block. Unlike <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a>, this macro works with <a href="ErrTryCatch.html#994145"><code>ErrThrowWithAddress()</code></a> to give the address reference that caused fault, if such an address.</p>
<h4>
  <a name="993185"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993202"> </a></code><h4>
  <a name="993222"> </a>Prototype 
</h4>
<pre class="proto"><a name="993259"></a>#define ErrCatchWithAddress (
   <code class="par">inErr</code>,
   <code class="par"> inErrVAddr</code>
)
</pre>
<h4>
  <a name="993299"> </a>Parameters 
</h4>

<dl>
<dt><a name="993342"> </a><code>&rarr;  <i>inErr</i></code></dt>
<dd><a name="999381"> </a>An exception code identifying the reason for the failure. This is the value supplied to the <a href="ErrTryCatch.html#994145"><code>ErrThrowWithAddress()</code></a> call that caused the jump to this <code>ErrCatch</code> block.</dd>

<dt><a name="993426"> </a><code>&rarr;  <i>inErrVAddr</i></code></dt>
<dd><a name="993468"> </a>Address reference that caused fault, if such an address is available.</dd>

</dl>
<h4>
  <a name="993470"> </a>Returns 
</h4>

<p><a name="999488"> </a>Returns nothing.</p>
<h4>
  <a name="993475"> </a>Comments 
</h4>

<p><a name="993478"> </a>If the exception was thrown with <a href="ErrTryCatch.html#993865"><code>ErrThrow()</code></a> or <a href="ErrTryCatch.html#993907"><code>ErrThrowIf()</code></a>, <code class="par">inErrVAddr</code> is set to <code>0xffffffff</code>.</p>

<p><a name="999605"> </a><code>ErrCatch</code> can only be used in conjunction with <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a> and <code>ErrEndCatch</code>. See the comments under <code>ErrTry</code> for usage instructions. Also see the comments under <code>ErrCatch</code> for information on changes to variables stored in registers.</p>

<h3 class="hbH3">
  <a name="995308"> </a>ErrEndCatch Macro <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="995806"> </a>Purpose 
</h4>

<p><a name="995331"> </a>Marks the end of an <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a> block.</p>
<h4>
  <a name="995332"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="995333"> </a></code><h4>
  <a name="995334"> </a>Prototype 
</h4>
<pre class="proto"><a name="995335"></a>#define ErrEndCatch
</pre>
<h4>
  <a name="995404"> </a>Parameters 
</h4>

<p><a name="995570"> </a>None.</p>
<h4>
  <a name="995606"> </a>Returns 
</h4>

<p><a name="995703"> </a>Returns nothing.</p>
<h4>
  <a name="995704"> </a>Comments 
</h4>

<p><a name="998312"> </a><code>EndErrCatch</code> can only be used in conjunction with <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a> and <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a> (or <a href="ErrTryCatch.html#993175"><code>ErrCatchWithAddress()</code></a>). See the comments under <code>ErrTry</code> for usage instructions.</p>

<h3 class="hbH3">
  <a name="993485"> </a>ErrExceptionListAppend Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="1000931"> </a>Purpose 
</h4>

<p><a name="1000932"> </a>Appends an exception to the exception list.</p>
<h4>
  <a name="1000933"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993498"> </a></code><h4>
  <a name="993500"> </a>Prototype 
</h4>
<pre class="proto"><a name="993503"></a>void ErrExceptionListAppend (
   ErrExceptionType <code class="par">*errExceptionTypeP</code>
)
</pre>
<h4>
  <a name="993505"> </a>Parameters 
</h4>

<dl>
<dt><a name="993508"> </a><code>&rarr;  <i>errExceptionTypeP</i></code></dt>
<dd><a name="993510"> </a>Pointer to the exception to be appended.</dd>

</dl>
<h4>
  <a name="993512"> </a>Returns 
</h4>

<p><a name="993515"> </a>Returns nothing.</p>
<h4>
  <a name="993522"> </a>See Also 
</h4>

<p><a name="993525"> </a><a href="ErrTryCatch.html#993527"><code>ErrExceptionListGetByThreadID()</code></a>, <a href="ErrTryCatch.html#993731"><code>ErrExceptionListRemove()</code></a></p>

<h3 class="hbH3">
  <a name="993527"> </a>ErrExceptionListGetByThreadID Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993532"> </a>Purpose 
</h4>

<p><a name="999736"> </a>Gets the head of the exception list for a given thread, without changing the list.</p>
<h4>
  <a name="993537"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993540"> </a></code><h4>
  <a name="993542"> </a>Prototype 
</h4>
<pre class="proto"><a name="993545"></a>ErrExceptionType *ErrExceptionListGetByThreadID (
   SysHandle <code class="par">iThreadID</code>
)
</pre>
<h4>
  <a name="993547"> </a>Parameters 
</h4>

<dl>
<dt><a name="993588"> </a><code>&rarr;  <i>iThreadID</i></code></dt>
<dd><a name="993634"> </a>ID of the thread for which the exception list is being obtained.</dd>

</dl>
<h4>
  <a name="993652"> </a>Returns 
</h4>

<p><a name="993719"> </a>Returns the exception at the head of the exception list.</p>
<h4>
  <a name="993721"> </a>Comments 
</h4>

<p><a name="1000385"> </a>This function is designed to be used by a keeper thread.</p>
<h4>
  <a name="993726"> </a>See Also 
</h4>

<p><a name="993729"> </a><a href="ErrTryCatch.html#993485"><code>ErrExceptionListAppend()</code></a>, <a href="ErrTryCatch.html#993731"><code>ErrExceptionListRemove()</code></a></p>

<h3 class="hbH3">
  <a name="993731"> </a>ErrExceptionListRemove Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993736"> </a>Purpose 
</h4>

<p><a name="993739"> </a>Removes a specified exception from the exception list.</p>
<h4>
  <a name="993741"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993744"> </a></code><h4>
  <a name="993746"> </a>Prototype 
</h4>
<pre class="proto"><a name="993749"></a>void ErrExceptionListRemove (
   ErrExceptionType <code class="par">*errExceptionTypeP</code>
)
</pre>
<h4>
  <a name="993751"> </a>Parameters 
</h4>

<dl>
<dt><a name="993754"> </a><code>&rarr;  <i>errExceptionTypeP</i></code></dt>
<dd><a name="993756"> </a>Pointer to the exception to be removed.</dd>

</dl>
<h4>
  <a name="993758"> </a>Returns 
</h4>

<p><a name="993761"> </a>Returns nothing.</p>
<h4>
  <a name="993768"> </a>See Also 
</h4>

<p><a name="993771"> </a><a href="ErrTryCatch.html#993485"><code>ErrExceptionListAppend()</code></a>, <a href="ErrTryCatch.html#993527"><code>ErrExceptionListGetByThreadID()</code></a></p>

<h3 class="hbH3">
  <a name="993773"> </a>ErrLongJump Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993778"> </a>Purpose 
</h4>

<p><a name="993781"> </a>Restores the environment saved in the specified buffer by a call to <a href="ErrTryCatch.html#993823"><code>ErrSetJump()</code></a>.</p>
<h4>
  <a name="993783"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993786"> </a></code><h4>
  <a name="993788"> </a>Prototype 
</h4>
<pre class="proto"><a name="993791"></a>void ErrLongJump (
   ErrJumpBuf <code class="par">buf</code>,
   int32_t <code class="par">result</code>
)
</pre>
<h4>
  <a name="993793"> </a>Parameters 
</h4>

<dl>
<dt><a name="993796"> </a><code>&rarr;  <i>buf</i></code></dt>
<dd><a name="1001374"> </a>Pointer to a buffer containing the environment to be restored ( program counter and stack pointer).</dd>

<dt><a name="993804"> </a><code>&rarr;  <i>result</i></code></dt>
<dd><a name="993806"> </a>Value that will appear to have been returned from <a href="ErrTryCatch.html#993823"><code>ErrSetJump()</code></a> once the environment has been restored.</dd>

</dl>
<h4>
  <a name="993808"> </a>Returns 
</h4>

<p><a name="993811"> </a>Returns nothing.</p>

<h3 class="hbH3">
  <a name="993823"> </a>ErrSetJump Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993828"> </a>Purpose 
</h4>

<p><a name="993831"> </a>Saves a copy of the current environment (program counter and the current pointer to the top of the stack) for later restoration by <a href="ErrTryCatch.html#993773"><code>ErrLongJump()</code></a>.</p>
<h4>
  <a name="993833"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993836"> </a></code><h4>
  <a name="993838"> </a>Prototype 
</h4>
<pre class="proto"><a name="993841"></a>int32_t ErrSetJump (
   ErrJumpBuf <code class="par">buf</code>
)
</pre>
<h4>
  <a name="993843"> </a>Parameters 
</h4>

<dl>
<dt><a name="993846"> </a><code>&rarr;  <i>buf</i></code></dt>
<dd><a name="993848"> </a>Pointer to a buffer in which the program counter and stack pointer are to be stored.</dd>

</dl>
<h4>
  <a name="993850"> </a>Returns 
</h4>

<p><a name="993853"> </a>Returns <code>errNone</code>. Note, however, that when a call to <a href="ErrTryCatch.html#993773"><code>ErrLongJump()</code></a> is made, the saved environment is restored, causing program execution to resume as if <code>ErrSetJump</code> had just returned; the value "returned "at that time is the one specified by the call to <code>ErrLongJump</code>.</p>

<h3 class="hbH3">
  <a name="993865"> </a>ErrThrow Macro <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993870"> </a>Purpose 
</h4>

<p><a name="998481"> </a>Cause a jump to the nearest catch block.</p>
<h4>
  <a name="993875"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993878"> </a></code><h4>
  <a name="993880"> </a>Prototype 
</h4>
<pre class="proto"><a name="993883"></a>#define ErrThrow (
   <code class="par">err</code>
)
</pre>
<h4>
  <a name="993885"> </a>Parameters 
</h4>

<dl>
<dt><a name="993888"> </a><code>&rarr;  <i>err</i></code></dt>
<dd><a name="993890"> </a>Error code.</dd>

</dl>
<h4>
  <a name="993892"> </a>Returns 
</h4>

<p><a name="993895"> </a>Never returns.</p>
<h4>
  <a name="993897"> </a>Comments 
</h4>

<p><a name="998516"> </a>Use the macros <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a>, <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a>, and <a href="ErrTryCatch.html#995308"><code>ErrEndCatch()</code></a> in conjunction with this function.</p>
<h4>
  <a name="993902"> </a>See Also 
</h4>

<p><a name="998584"> </a><a href="ErrorMgr.html#993250"><code>ErrFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993590"><code>ErrNonFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993086"><code>ErrDisplay()</code></a> </p>

<h3 class="hbH3">
  <a name="993907"> </a>ErrThrowIf Macro <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="993912"> </a>Purpose 
</h4>

<p><a name="993915"> </a>If the error code parameter is other than <code>errNone</code>, cause a jump to the nearest catch block.</p>
<h4>
  <a name="993929"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="993950"> </a></code><h4>
  <a name="993974"> </a>Prototype 
</h4>
<pre class="proto"><a name="994001"></a>#define ErrThrowIf (
   <code class="par">err</code>
)
</pre>
<h4>
  <a name="994027"> </a>Parameters 
</h4>

<dl>
<dt><a name="994054"> </a><code>&rarr;  <i>err</i></code></dt>
<dd><a name="994080"> </a>Error code.</dd>

</dl>
<h4>
  <a name="994106"> </a>Returns 
</h4>

<p><a name="994133"> </a>Never returns.</p>
<h4>
  <a name="994135"> </a>Comments 
</h4>

<p><a name="998761"> </a>Use the macros <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a>, <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a>, and <a href="ErrTryCatch.html#995308"><code>ErrEndCatch()</code></a> in conjunction with this function.</p>
<h4>
  <a name="994140"> </a>See Also 
</h4>

<p><a name="1002175"> </a><a href="ErrorMgr.html#993250"><code>ErrFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993590"><code>ErrNonFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993086"><code>ErrDisplay()</code></a> </p>

<h3 class="hbH3">
  <a name="994145"> </a>ErrThrowWithAddress Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="994150"> </a>Purpose 
</h4>

<p><a name="999079"> </a>Throw an error to the first handler on the exception list for this thread, causing a jump to the nearest catch block. Unlike <a href="ErrTryCatch.html#993865"><code>ErrThrow()</code></a> and <a href="ErrTryCatch.html#993907"><code>ErrThrowIf()</code></a>, you can use this function to pass the address reference that caused the fault.</p>
<h4>
  <a name="994155"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="994158"> </a></code><h4>
  <a name="994160"> </a>Prototype 
</h4>
<pre class="proto"><a name="994163"></a>void ErrThrowWithAddress (
   int32_t <code class="par">err</code>,
   VAddr <code class="par">errVAddr</code>
)
</pre>
<h4>
  <a name="994165"> </a>Parameters 
</h4>

<dl>
<dt><a name="994168"> </a><code>&rarr;  <i>err</i></code></dt>
<dd><a name="999015"> </a>Error code.</dd>

<dt><a name="994172"> </a><code>&rarr;  <i>errVAddr</i></code></dt>
<dd><a name="994174"> </a>Address to be reported to <a href="ErrTryCatch.html#993175"><code>ErrCatchWithAddress()</code></a>.</dd>

</dl>
<h4>
  <a name="994176"> </a>Returns 
</h4>

<p><a name="999027"> </a>Never returns.</p>
<h4>
  <a name="994181"> </a>Comments 
</h4>

<p><a name="1001156"> </a>Use the macros <a href="ErrTryCatch.html#992930"><code>ErrTry()</code></a>, <a href="ErrTryCatch.html#993175"><code>ErrCatchWithAddress()</code></a>, and <a href="ErrTryCatch.html#995308"><code>ErrEndCatch()</code></a> in conjunction with this function.</p>
<h4>
  <a name="994186"> </a>See Also 
</h4>

<p><a name="1002202"> </a><a href="ErrorMgr.html#993250"><code>ErrFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993590"><code>ErrNonFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993086"><code>ErrDisplay()</code></a> </p>

<h3 class="hbH3">
  <a name="994191"> </a>ErrThrowWithHandler Function <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="994196"> </a>Purpose 
</h4>

<p><a name="999031"> </a>This function is what the keeper thread should make the faulted thread run when it resumes.  This function will do the <a href="ErrTryCatch.html#993773"><code>ErrLongJump()</code></a> to make the faulted thread clear its stack and jump to its <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a> handler.</p>
<h4>
  <a name="994201"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="994204"> </a></code><h4>
  <a name="994206"> </a>Prototype 
</h4>
<pre class="proto"><a name="994209"></a>void ErrThrowWithHandler (
   int32_t <code class="par">err</code>,
   VAddr <code class="par">errVAddr</code>,
   ErrExceptionType <code class="par">*tryP</code>
)
</pre>
<h4>
  <a name="994211"> </a>Parameters 
</h4>

<dl>
<dt><a name="994214"> </a><code>&rarr;  <i>err</i></code></dt>
<dd><a name="999061"> </a>Error code.</dd>

<dt><a name="994222"> </a><code>&rarr;  <i>errVAddr</i></code></dt>
<dd><a name="1001896"> </a>Address to be reported to <a href="ErrTryCatch.html#993175"><code>ErrCatchWithAddress()</code></a>.</dd>

<dt><a name="994274"> </a><code>&rarr;  <i>tryP</i></code></dt>
<dd><a name="994276"> </a>Pointer to the exception state to be handled by <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a> or <a href="ErrTryCatch.html#993175"><code>ErrCatchWithAddress()</code></a>.</dd>

</dl>
<h4>
  <a name="994278"> </a>Returns 
</h4>

<p><a name="999047"> </a>Never returns.</p>
<h4>
  <a name="994283"> </a>Comments 
</h4>

<p><a name="994286"> </a>This function is designed to be used by a keeper thread.</p>
<h4>
  <a name="994288"> </a>See Also 
</h4>

<p><a name="1002217"> </a><a href="ErrorMgr.html#993250"><code>ErrFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993590"><code>ErrNonFatalDisplayIf()</code></a>, <a href="ErrorMgr.html#993086"><code>ErrDisplay()</code></a> </p>

<h3 class="hbH3">
  <a name="992930"> </a>ErrTry Macro <a href="#992934"><span class="nav">^TOP^</span></a>
</h3>

<h4>
  <a name="995732"> </a>Purpose 
</h4>

<p><a name="995783"> </a>Marks the beginning of a try/catch block.</p>
<h4>
  <a name="995784"> </a>Declared In 
</h4>
<code>ErrTryCatch.h<a name="995785"> </a></code><h4>
  <a name="995740"> </a>Prototype 
</h4>
<pre class="proto"><a name="995746"></a>#define ErrTry
</pre>
<h4>
  <a name="995760"> </a>Parameters 
</h4>

<p><a name="995763"> </a>None.</p>
<h4>
  <a name="995764"> </a>Returns 
</h4>

<p><a name="995769"> </a>Returns nothing.</p>
<h4>
  <a name="995770"> </a>Comments 
</h4>

<p><a name="998828"> </a>An exception raised by a call to <a href="ErrTryCatch.html#993865"><code>ErrThrow()</code></a>&#8212;even from within a nested subroutine&#8212;causes program execution to switch to the beginning of the <a href="ErrTryCatch.html#993133"><code>ErrCatch()</code></a> block. If the end of the block enclosed by <code>ErrTry</code> is encountered without a call to <code>ErrThrow</code>, execution jumps to the line of code following the <a href="ErrTryCatch.html#995308"><code>ErrEndCatch()</code></a> macro. See <a href="Debugging.html#1023494">"The Try-and-Catch Mechanism"</a> for a more thorough description of how this mechanism works.</p>
<h4>
  <a name="998841"> </a>Example 
</h4>

<p><a name="998842"> </a>You must structure your code exactly as shown here. You can't use <code>ErrTry</code> without <code>ErrCatch</code> and <code>ErrEndCatch</code>, or vice versa.</p>

<div class="CodeRule"><hr></div><pre class="CodeBlock">
ErrTry {<a name="998843"> </a>
   // Do something which may fail. Call ErrThrow to signal
   // failure and force a jump to the following ErrCatch
   // block.<a name="998844"> </a>
} <a name="998845"> </a>
ErrCatch(inErr) {<a name="998846"> </a>
   // Recover or cleanup after a failure in the above ErrTry
   // block. "inErr" is an exception code identifying the
   // reason for the failure.<a name="998847"> </a>
 <a name="998848"> </a>
   // Call ErrThrow if you want to jump out to the next
   // ErrCatch block.<a name="998849"> </a>
 <a name="998850"> </a>
   // The code in this block doen't execute if the above
   // ErrTry block completes without a call to ErrThrow.<a name="998851"> </a>
} ErrEndCatch<a name="998852"> </a>
</pre><div class="CodeRule"><hr></div>

<pre class="proto"><a name="995742"></a>
</pre>
&nbsp;<br>
</div>
<!--END CONTENT-->

</td>
<td width="5">&nbsp;&nbsp;</td>
</tr>

</table>

<!-- BEGIN FOOTER -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="7" rowspan="2"><img name="index_x" src="images/shim.gif" width="7" height="33" border="0" alt=""></td>
<td align="left"><img name="dashes" src="images/dashes.gif" width="744" height="3" border="0" alt=""></td>
<td width="10" rowspan="2"><img name="index_x" src="images/shim.gif" width="10" height="33" border="0" alt=""></td>
</tr>
<tr>
<td align="center">
<p class="footer">
Copyright © 1996&#8211;2004, PalmSource, Inc. and its affiliates. All rights reserved.<br>
<a href="http://www.palmsource.com/contact/">Write Us</a> | <a href="http://www.palmos.com/dev/training/">Training</a> | <a href="http://www.palmos.com/dev/support/kb/">Knowledge Base</a> | <a href="SysMgt_Front.html" target="_blank">Legal</a></p>
<br>
<!--BEGIN BOOK NAVIGATION-->
<p class="nav">
<A href="http://www.palmos.com/dev/support/docs/">Documentation</a>&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="SysMgt_TOC.html">Table of Contents</a>&nbsp;&nbsp;
             |&nbsp;&nbsp;<a href="ErrorMgr.html">&lt;&nbsp;Previous</a>&nbsp;&nbsp;
             |&nbsp;&nbsp;<a href="ExpansionMgr.html">Next&nbsp;&gt;</a>&nbsp;&nbsp;
             |&nbsp;&nbsp;<a href="SysMgt_IX.html">Index</a>
</p>
</td>
</tr>
</table>
<!-- END FOOTER -->

</body>
</html>